name: CI

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'MeilCli/Librarian'
          ref: 'master'
          path: 'Librarian'
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        name: Cache Gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('Librarian/buildSrc/build.gradle.kts') }}-${{ hashFiles('Librarian/buildSrc/src/**') }}-${{ hashFiles('Librarian/dependencies/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('Librarian/buildSrc/build.gradle.kts') }}-${{ hashFiles('Librarian/buildSrc/src/**') }}-
            ${{ runner.os }}-gradle-${{ hashFiles('Librarian/buildSrc/build.gradle.kts') }}-
            ${{ runner.os }}-gradle-
      - name: Grant permission
        run: chmod +x Librarian/gradlew
      - run: cd Librarian && ./gradlew lintDebug
      - uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: |
            Librarian/reports/lint/**/**.xml
      - uses: MeilCli/android-lint-statistics@master
        with:
          lint_xml_file_path: 'Librarian/reports/lint/**/**.xml'
      - uses: actions/upload-artifact@v2
        with:
          name: lint-result
          path: |
            Librarian/data.png
            Librarian/severity.png
            Librarian/priority.png
            Librarian/report.json
            Librarian/report.txt
